spring:
  application:
    # 应用名
    name: network-mall
  profiles:
    active: test

  data:
    # Redis 配置
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456

  #---------------------数据库配置---------------------------
  datasource:
    url: jdbc:mysql://aws.gedune.space:23306/shop_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Gedune150.

  mail:
    host: 123
    #发件人昵称
    nickname: 123@QQ.com
    #邮箱账户
    username: 123@QQ.com
    #邮箱第三方授权码
    password: 123456
    #编码类型
    default-encoding: UTF-8
    port: 123456

  # RabbitMQ 配置
  rabbitmq:
    host: test.com # RabbitMQ 服务器地址
    port: 12345 # RabbitMQ 端口
    username: 123 # RabbitMQ 用户名
    password: 123456 # RabbitMQ 密码
    virtual-host: / # 虚拟主机，默认是 "/"
    connection-timeout: 60000 # 连接超时时间（单位：毫秒）
    listener:
      simple:
        prefetch: 10 # 每个消费者预取的消息数量
        concurrency: 5 # 最小消费者数量
        max-concurrency: 10 # 最大消费者数量
        retry:
          enabled: true # 是否启用重试机制
          max-attempts: 6 # 最大重试次数
          initial-interval: 1000 # 重试间隔时间（单位：毫秒）
  task:
    execution:
      pool:
        core-size: 5
        max-size: 20
        queue-capacity: 100
payment:
  alipay:
    app-id: wx1234567890
    alipay-public-key: 1230000109
    private-key: your-api-key
    server-url: https://openapi.alipay.com/gateway.do
    notify-url: https://test.com/alipay/notify

---

---
#---------------------自定义配置----------------------------
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: token
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
network:
  # 跨域配置
  # cors:
  #   # 允许跨域的域名
  #   allow-origins:
  #     - http://localhost:1024
  #     - http://localhost:8080

  # XSS 过滤配置
  xss:
    # 过滤开关
    enabled: true
    # 排除链接
    excludes:
      # - /system/notice/*
---
#--------------------接口文档配置---------------------------
springdoc:
  api-docs:
    enabled: true

cors:
  allowedOrigins:
    - "http://localhost"

logging:
  level:
    root: info   #主日志级别
    # com.hasikiFire.networkmall: debug   #该项目日志级别，当需要打印sql时请开启为debug
  path: ./logs